# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4677be2aef2e1f6f613b8c80882d89cbdd9d7acead31b22b8fec8345ca015c8a005f5e2d4d95032fb86af5b31e44c1218649f20259481342846720c58c0fbf71

test:
  secret_key_base: b02d5bdb7576463a0b08c12ba113a9003a9dd366fe7ca4d463006970d7642ef0620736eb4d8a9d8e916e0863e8b8f9213590b0578fd811b856cfb07b811c8d01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
